// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tool_Website.data;

namespace Tool_Website.data.Migrations
{
    [DbContext(typeof(toolcontext))]
    [Migration("20210514063845_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Tool_Website.Models.product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A flat screwdriver, useful for any situation!",
                            ImageName = "flat.jpg",
                            Name = "Flat Screwdriver",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A diamond screwdriver, for those difficult screws!",
                            ImageName = "star.jpg",
                            Name = "Diamond Screwdriver",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A hammer, for hitting those screws in place!",
                            ImageName = "hammer.png",
                            Name = "Hammer",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pliers, useful for stripping wires!",
                            ImageName = "pliers.jpg",
                            Name = "Pliers",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A shovel, trying to dig a hole? This is perfect for you!",
                            ImageName = "shovel.jpg",
                            Name = "Shovel",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A wrench, for tighting and lossing those boltss!",
                            ImageName = "wrench.jpg",
                            Name = "Wrench",
                            Price = 7.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
